name: Create FromA2B Api Client & Publish NPM Package

on:
  push:
    branches: [master, develop, features/*]

jobs:
  ApiClient:
    name: Generate API Client
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      actions: read

    outputs:
      npm_version: ${{ steps.get_npm_version.outputs.NPM_VERSION }}
      npm_tag: ${{ steps.setup_npm_tag.outputs.NPM_TAG }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup npmTag
        id: setup_npm_tag
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "::set-output name=NPM_TAG::-RC"
          elif [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            echo "::set-output name=NPM_TAG::-Beta"
          elif [ "${{ github.ref }}" = refs/heads/features/* ]; then
            echo "::set-output name=NPM_TAG::-Alpha"
          fi

      - name: Get Latest Version
        id: get_latest_version
        run: |
          latest_version=$(git describe --tags --abbrev=0)
          echo "::set-output name=LATEST_VERSION::$latest_version"

      - name: Increment Version
        id: increment_version
        run: |
          # Extract major, minor, and patch version numbers
          major=$(echo "${{ steps.get_latest_version.outputs.LATEST_VERSION }}" | cut -d. -f1)
          minor=$(echo "${{ steps.get_latest_version.outputs.LATEST_VERSION }}" | cut -d. -f2)
          patch=$(echo "${{ steps.get_latest_version.outputs.LATEST_VERSION }}" | cut -d. -f3)

          # Increment version based on branch
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            ((minor++))
          elif [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            ((patch++))
          elif [[ "${{ github.ref }}" == refs/heads/features/* ]]; then
            ((patch++))
          fi

          # Construct the new version
          new_version="$major.$minor.$patch"
          echo "::set-output name=NEW_VERSION::$new_version"

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://npm.pkg.github.com/

      - name: install Open Api Tool CLI
        run: npm install @openapitools/openapi-generator-cli -g

      - name: Create API Client
        run: |
          openapi-generator-cli generate -i ./Map.Api/wwwroot/swagger/swagger.json \
          -g typescript-axios -c ./generatorConfig.json -o ./FromA2B_Api_Client/ \
          --additional-properties=npmVersion=${{ steps.get_npm_version.outputs.NPM_VERSION }}${{ steps.setup_npm_tag.outputs.NPM_TAG }} \
          --additional-properties=npmRepository=https://npm.pkg.github.com

      - name: Upload API Client Artifact
        uses: actions/upload-artifact@v2
        with:
          name: api-client
          path: ./FromA2B_Api_Client

  NpmPackage:
    name: Build and Publish NPM Package
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: read

    needs: ApiClient

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download API Client Artifact
        uses: actions/download-artifact@v2
        with:
          name: api-client
          path: ./FromA2B_Api_Client

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Update Package.json
        uses: restackio/update-json-file-action@v2.0
        with:
          file: ./FromA2B_Api_Client/package.json
          fields: '{"files": ["dist/"]}'

      - name: Set NPM Token
        working-directory: ./FromA2B_Api_Client
        run: echo "//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}">.npmrc

      - name: Install npm dependencies and build
        working-directory: ./FromA2B_Api_Client
        run: |
          npm install
          npm run build

      - name: Publish API Client
        working-directory: ./FromA2B_Api_Client
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
