name: Create FromA2B Api Client

on:
  push:
    branches: [master, develop, features/*]

env:
  npmTag: ''

jobs:
  ApiClient:
    name: Build And Create Api Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup npmTag to -Beta
        if: github.ref_name == github.ref_name
        # if: github.ref_name == 'develop'
        run: echo "npmTag=-Beta" >> $GITHUB_ENV

      - name: Install Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://npm.pkg.github.com/

      - name: install Open Api Tool CLI
        run: npm install @openapitools/openapi-generator-cli -g

      - name: Get Variable value
        run: echo "NPM_PACKAGE_VERSION=$(node -p "require('./npmVersion.json').version")" >> $GITHUB_ENV

      - name: Create API Client
        run: openapi-generator-cli generate -i ./Map.Api/wwwroot/swagger/swagger.json -g typescript-axios -c ./generatorConfig.json -o ./FromA2B_Api_Client/ --additional-properties=npmVersion=${{ env.NPM_PACKAGE_VERSION }}${{ env.npmTag }} --additional-properties=npmRepository=https://npm.pkg.github.com

      - name: Add Files To Packagejson
        uses: restackio/update-json-file-action@v2.0
        with:
          file: ./FromA2B_Api_Client/package.json
          fields: '{"files": ["dist/"]}'
        
      - name: Set NPM Token
        working-directory: ./FromA2B_Api_Client
        run: echo "//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}">.npmrc

      - name: Install npm package
        working-directory: ./FromA2B_Api_Client
        run: npm install

      - name: Build client API
        working-directory: ./FromA2B_Api_Client
        run: npm run build

      - name: Get Variable value
        working-directory: ./FromA2B_Api_Client
        run: |
          echo "NPM_PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          echo "NPM_PACKAGE_NAME=$(node -p "require('./package.json').name")" >> $GITHUB_ENV

      - name: Create NPM publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
