name: Create FromA2B Api Client & Publish NPM Package

on:
  push:
    branches:
      - main
      - develop
      - features/*
  release:
    types: [created]

jobs:
  ApiClient:
    name: Generate API Client
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      actions: read
    env:
      USE_IN_MEMORY_DATABASE: True

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout FromA2B Repository
        uses: actions/checkout@v2
        with:
          repository: FullStackMap/FromA2BClient
          ref: refs/heads/features
          path: ./FromA2B_Api_Client
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Install .Net 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x.x'

      - name: create manifest
        run: dotnet new tool-manifest

      - name: Install Nuget Package
        run: dotnet tool install Swashbuckle.AspNetCore.Cli

      - name: install Open Api Tool CLI
        run: npm install @openapitools/openapi-generator-cli -g

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://npm.pkg.github.com/

      - name: install semver
        run: npm install semver

      - name: Restore Tools
        run: dotnet tool restore

      - run: ls -R

      - name: .Net Build
        uses: EasyDesk/action-dotnet-build@v1.0.0
        with:
          path: ./Map.sln

      - name: Generate Swagger.json
        run: dotnet swagger tofile --output ./swagger.json ./Map.Api/bin/Release/net8.0/Map.API.dll v1

      - name: Get NPM Package Version
        id: get_npm_version
        working-directory: ./FromA2B_Api_Client
        run: echo "::set-output name=NPM_VERSION::$(node -p "require('./package.json').version")"

      - name: Setup npmTag
        id: setup_npm_tag
        run: |
          case "${{ github.ref }}" in
            refs/heads/features/*)
              echo "::set-output name=NPM_TAG::-Alpha"
              ;;
            "refs/heads/develop")
              echo "::set-output name=NPM_TAG::-Beta"
              ;;
            "refs/heads/main")
              echo "::set-output name=NPM_TAG::-RC"
              ;;
          esac

      - name: Setup new version
        id: setup_new_version
        run: |
          case "${{ github.ref }}" in
            refs/heads/features/* )
              echo ::set-output name=NEW_VERSION::$(node -e "console.log(require('semver').inc('${{ steps.get_npm_version.outputs.NPM_VERSION }}', 'patch'))")
              ;;
            "refs/heads/develop")
              echo ::set-output name=NEW_VERSION::$(node -e "console.log(require('semver').inc('${{ steps.get_npm_version.outputs.NPM_VERSION }}', 'minor'))")
              ;;
            "refs/heads/main")
              echo ::set-output name=NEW_VERSION::$(node -e "console.log(require('semver').inc('${{ steps.get_npm_version.outputs.NPM_VERSION }}', 'major'))")
              ;;
          esac

      - name: Create API Client
        run: |
          openapi-generator-cli generate -i ./Map.Api/wwwroot/swagger/swagger.json \
          -g typescript-axios -c ./generatorConfig.json -o ./FromA2B_Api_Client/ \
          --additional-properties=npmVersion=${{ steps.setup_new_version.outputs.NEW_VERSION }}${{ steps.setup_npm_tag.outputs.NPM_TAG }} \
          --additional-properties=npmRepository=https://npm.pkg.github.com

      - name: Add File To Packagejson
        uses: restackio/update-json-file-action@v2.0
        with:
          file: ./FromA2B_Api_Client/package.json
          fields: '{"files": ["dist"]}'

      - name: count nb change in FromA2B_Api_Client repo
        id: countChange
        run: echo "nbChange=$(git diff --name-status | grep "^[MARD]" | wc -l)" >> $GITHUB_OUTPUT
        working-directory: ./FromA2B_Api_Client

      - name: Push to FromA2B_Api_Client if have modification
        if: ${{ steps.countChange.outputs.nbChange != 0}}
        working-directory: ./FromA2B_Api_Client
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Update FromA2B Client V${{ env.NPM_PACKAGE_VERSION }}${{ env.npmTag }}"
          git push origin HEAD:refs/heads/features
