name: Create FromA2B Api Client

on:
  push:
    branches: [master, develop, features/*]

env:
  npmTag: ''

jobs:
  ApiClient:
    name: Build And Create Api Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup npmTag to -Beta
        if: github.ref_name == github.ref_name
        # if: github.ref_name == 'develop'
        run: echo "npmTag=-Beta" >> $GITHUB_ENV

      - name: Install Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: install Open Api Tool CLI
        run: npm install @openapitools/openapi-generator-cli -g

      - name: Get Variable value
        run: echo "NPM_PACKAGE_VERSION=$(node -p "require('./npmVersion.json').version")" >> $GITHUB_ENV

      - name: Create API Client
        run: openapi-generator-cli generate -i ./Map.API/wwwroot/swagger/swagger.json -g typescript-axios -o ./FromA2B_Api_Client/ --additional-properties=npmVersion=${{ env.NPM_PACKAGE_VERSION }}${{ env.npmTag }} --additional-properties=npmRepository=https://npm.pkg.github.com

      - name: Add Files To Packagejson
        uses: restackio/update-json-file-action@v2.0
        with:
          file: ./FromA2B_Api_Client/package.json
          fields: '{"files": ["dist"]}'
